Req OLTSWITCH-1203 Adapted fastpath script to version 3.11.x
svn path=/branches/switchdrvr-4.0/; revision=7067

diff --git a/src/builds/tmp/TA12XG/rootfs/usr/local/ptin/sbin/fastpath b/src/builds/tmp/TA12XG/rootfs/usr/local/ptin/sbin/fastpath
--- a/src/builds/tmp/TA12XG/rootfs/usr/local/ptin/sbin/fastpath
+++ b/src/builds/tmp/TA12XG/rootfs/usr/local/ptin/sbin/fastpath
@@ -5,7 +5,6 @@ mode="run"
 app_name=switchdrvr
 app_path=/usr/local/ptin/sbin/$app_name
 cli=/usr/local/ptin/sbin/fp.cli
-startup_log=/usr/local/ptin/log/fastpath/startup.log
 proc_txt=/usr/local/ptin/log/fastpath/proc.txt
 ntry=0
 
@@ -28,11 +27,8 @@ insert_modules()
 
 startup()
 {
-    # Add header info to startup log file
-    echo "*************************************************************" >> $startup_log
-    echo "FASTPATH STARTED AT: `date` [retry $ntry]" >> $startup_log
-    ps >> $startup_log
-    free >> $startup_log
+    # Create folder for switchdrvr output 
+    mkdir -p /var/log/switchdrvr
 
     # Insert modules
     insert_modules;
@@ -41,9 +37,9 @@ startup()
     $app_path 0>/dev/null &
 
     # Wait 200 seconds for FP to boot up
-    $cli ping p=20 t=10
+    #$cli ping p=20 t=10
 
-    let "ntry=ntry+1"
+    #let "ntry=ntry+1"
 }
 
 # If no options, define default mode
@@ -79,43 +75,30 @@ elif [ $mode = "boot" ]; then
         exit 1;
     fi
     
-    # Handle startup log oversize issues
-    filesize=`du $startup_log`
-    if [ "$?" -eq "0" ]; then
-        filesize=`echo $filesize | awk '{print $1}'`
-        echo "File $startup_log has a size of $filesize KB"
-    else
-        filesize=0;
-    fi
-    if [ $filesize -gt "2048" ]; then
-      echo "Move file $startup_log => startup_log.old"
-      mv -f $startup_log $startup_log.old
-    fi
-
     # Query application to determine if it is running or not
-    $cli ping p=4 t=6 > /dev/null
+    #$cli ping p=4 t=6 > /dev/null
     # Start application
-    if [ "$?" -ne "0" ]; then
+    #if [ "$?" -ne "0" ]; then
         echo "Going to start application"
         startup;
-    fi
+    #fi
 
     # Working loop...
-    while [ 1 ]
-    do
+    #while [ 1 ]
+    #do
         # Query application to determine if it is running or not
-        $cli ping p=12 t=10 > /dev/null
-        if [ "$?" -ne "0" ]; then
-            echo "Transferring LOGs to Matrix board..."
-            echo "Fastpath watchdog fired after 10x12 seconds of inactivity!" > /var/log/system_error_info.log
-            /bin/sh /usr/local/ptin/scripts/transfer_logs.sh
-            echo "Rebooting board"
-            reboot;
-            exit;
-        else
-            sleep 30
-        fi
-    done
+        #$cli ping p=12 t=10 > /dev/null
+        #if [ "$?" -ne "0" ]; then
+        #    echo "Transferring LOGs to Matrix board..."
+        #    echo "Fastpath watchdog fired after 10x12 seconds of inactivity!" > /var/log/system_error_info.log
+        #    /bin/sh /usr/local/ptin/scripts/transfer_logs.sh
+        #    echo "Rebooting board"
+        #    reboot;
+        #    exit;
+        #else
+        #    sleep 30
+        #fi
+    #done
 
 # No option (normal launch)
 else
