Task OLTSWITCH-1121 Task OLTOSNG-259 Main makefile refactored to allow full parallel compilation Fastpath makefile updated to ignore output/.../libs-ptin directory for cleanall target make.cfg corrected to accomodate all CPUs/cards Debug directory removed (obsolete files) libs-ptin ignored for TA48GE *.log files ignored on main fastpath directory
svn path=/branches/3.11_multiBoardProc/; revision=6455

diff --git a/src/fastpath/Makefile b/src/fastpath/Makefile
--- a/src/fastpath/Makefile
+++ b/src/fastpath/Makefile
@@ -7,180 +7,93 @@
 #                                              #
 ################################################
 
-.PHONY: help h all install clean cleanall
+# List of all supported cards
+cards = cxo640g cxo160g ta48ge tg16g tg16gf tt04sxg olt1t0 olt1t0f
 
-SVN_REV := $(shell svnversion -n | sed -e 's/.*://' -e 's/[A-Z]*$$//')
 
-version = "test"
+######################## Do not change any line below ########################
 
-IMAGE_DIR       = ../../builds
+.PHONY: help h all install clean cleanall release
 
 help h:
 	@echo ""
-	@echo "Makefile Help            "
+	@echo "Fastpath Makefile Help                         "
 	@echo ""
-	@echo " make all                "
-	@echo " make clean              "
-	@echo " make cleanall           "
-	@echo " make install            "
+	@echo " Supported cards:                              "
+	@echo "  $(cards)"
 	@echo ""
-	@echo " make cxo640g            "
-	@echo " make cxo160g            "
-	@echo " make ta48ge             "
-	@echo " make tg4g               "
-	@echo " make tg16g              "
-	@echo " make tg16gf             "
-	@echo " make tt04sxg            "
-	@echo " make olt1t0             "
-	@echo " make olt1t0f            "
+	@echo " Global targets:                               "
+	@echo "  make all         build all cards             "
+	@echo "       clean       clean all cards             "
+	@echo "       cleanall    cleanall all cards          "
+	@echo "       install     install all cards           "
+	@echo "       release     all+install, in sequence    "
 	@echo ""
-	@echo " make cxo640g-clean      "
-	@echo " make cxo160g-clean      "
-	@echo " make ta48ge-clean       "
-	@echo " make tg4g-clean         "
-	@echo " make tg16g-clean        "
-	@echo " make tg16gf-clean       "
-	@echo " make tt04sxg-clean      "
-	@echo " make olt1t0-clean       "
-	@echo " make olt1t0f-clean      "
+	@echo " Individual card targets:                      "
+	@echo "  make <card>                                  "
+	@echo "  make clean-<card>                            "
+	@echo "  make cleanall-<card>                         "
+	@echo "  make install-<card>                          "
+	@echo "  make release-<card>                          "
 	@echo ""
-	@echo " make cxo640g-cleanall   "
-	@echo " make cxo160g-cleanall   "
-	@echo " make ta48ge-cleanall    "
-	@echo " make tg4g-cleanall      "
-	@echo " make tg16g-cleanall     "
-	@echo " make tg16gf-cleanall    "
-	@echo " make tt04sxg-cleanall   "
-	@echo " make olt1t0-cleanall    "
-	@echo " make olt1t0f-cleanall   "
-	@echo ""
-	@echo " make cxo640g-install    "
-	@echo " make cxo160g-install    "
-	@echo " make ta48ge-install     "
-	@echo " make tg4g-install       "
-	@echo " make tg16g-install      "
-	@echo " make tg16gf-install     "
-	@echo " make tt04sxg-install    "
-	@echo " make olt1t0-install     "
-	@echo " make olt1t0f-install    "
+	@echo " NOTE: by default -j<MAX_CPU> is used          "
 	@echo ""
 	
-all: cxo640g cxo160g ta48ge tg16g tg16gf tt04sxg olt1t0 olt1t0f
+# Set by default to use the maximum CPUs available
+export MAKEFLAGS += -j `grep -c '^processor' /proc/cpuinfo`
 
-clean: cxo640g-clean cxo160g-clean ta48ge-clean tg4g-clean tg16g-clean tg16gf-clean tt04sxg-clean olt1t0-clean olt1t0f-clean
+# Disable jobserver if multiple targets are detected
+ifneq ($(words $(MAKECMDGOALS)), 0)
+ifneq ($(words $(MAKECMDGOALS)), 1)
+.NOTPARALLEL:
+$(info WARNING: multiple targets detected. disabling jobserver mode)
+endif
+endif
 
-cleanall: cxo640g-cleanall cxo160g-cleanall ta48ge-cleanall tg4g-cleanall tg16g-cleanall tg16gf-cleanall tt04sxg-cleanall olt1t0-cleanall olt1t0f-cleanall
+# Global targets
+all: $(cards)
 
-install: cxo640g-install cxo160g-install ta48ge-install tg16g-install tg16gf-install tt04sxg-install olt1t0-install olt1t0f-install
+clean: $(addprefix clean-,$(cards))
 
+cleanall: $(addprefix cleanall-,$(cards))
 
-cxo640g:
-	@$(MAKE) -f swdrvr-cxo640g.make
+install: $(addprefix install-,$(cards))
 
-cxo160g:
-	@$(MAKE) -f swdrvr-cxo160g.make
+release:
+	@$(MAKE) all
+	@$(MAKE) install
 
-ta48ge:
-	@$(MAKE) -f swdrvr-ta48ge.make
-	
-tg4g:
-	@$(MAKE) -f swdrvr-tg4g.make
+# Individual targets
+$(cards):
+	@echo "$@ compilation started (log file $@.make.log)"
+	@{ time $(MAKE) -f swdrvr-$@.make > $@.make.log 2>&1; } 2>.$@.make.time; echo "make-retval $$?" >> .$@.make.time;
 
-tg16g:
-	@$(MAKE) -f swdrvr-tg16g.make
-	
-tg16gf:
-	@$(MAKE) -f swdrvr-tg16gf.make
-	
-tt04sxg:
-	@$(MAKE) -f swdrvr-tt04sxg.make
-	
-olt1t0:
-	@$(MAKE) -f swdrvr-olt1t0.make
-	
-olt1t0f:
-	@$(MAKE) -f swdrvr-olt1t0f.make
+	@{ ret=`cat .$@.make.time | grep 'make-retval' | awk '{print $$2}'`;\
+	time=`cat .$@.make.time | grep 'real' | awk '{print $$2}'`;\
+	if [ "$$ret" != "0" ]; then \
+		echo "$@ compilation finished with errors in $${time}. Please see log file $@.make.log for more details"; \
+	else \
+		echo "$@ compilation finished successfully in $${time}"; \
+	fi; \
+	rm .$@.make.time; }
 
+$(addprefix clean-, $(cards)):
+	@echo "$@ started (log: $(subst clean-,,$@).clean.log)"
+	@$(MAKE) -f swdrvr-$(subst clean-,,$@).make clean > $(subst clean-,,$@).clean.log 2>&1
+	@echo "$@ done!"
+	
+$(addprefix cleanall-, $(cards)):
+	@echo "$@ started (log: $(subst cleanall-,,$@).cleanall.log)"
+	@$(MAKE) -f swdrvr-$(subst cleanall-,,$@).make cleanall > $(subst clean-,,$@).cleanall.log 2>&1
+	@echo "$@ done!"
+	
+$(addprefix install-, $(cards)):
+	@echo "$@ started (log: $(subst install-,,$@).install.log)"
+	@sh $(subst install-,,$@).install  > $(subst clean-,,$@).install.log 2>&1
+	@echo "$@ done!"
 
-cxo640g-clean:
-	@$(MAKE) -f swdrvr-cxo640g.make clean
+$(addprefix release-, $(cards)):
+	@echo "Doing $@"
+	@$(MAKE) $(subst release-,,$@)
+	@$(MAKE) $(subst release,install,$@)
 
-cxo160g-clean:
-	@$(MAKE) -f swdrvr-cxo160g.make clean
-
-ta48ge-clean:
-	@$(MAKE) -f swdrvr-ta48ge.make clean
-	
-tg4g-clean:
-	@$(MAKE) -f swdrvr-tg4g.make clean
-
-tg16g-clean:
-	@$(MAKE) -f swdrvr-tg16g.make clean
-	
-tg16gf-clean:
-	@$(MAKE) -f swdrvr-tg16gf.make clean
-	
-tt04sxg-clean:
-	@$(MAKE) -f swdrvr-tt04sxg.make clean
-	
-olt1t0-clean:
-	@$(MAKE) -f swdrvr-olt1t0.make clean
-	
-olt1t0f-clean:
-	@$(MAKE) -f swdrvr-olt1t0f.make clean
-
-	
-cxo640g-cleanall:
-	@$(MAKE) -f swdrvr-cxo640g.make cleanall
-
-cxo160g-cleanall:
-	@$(MAKE) -f swdrvr-cxo160g.make cleanall
-
-ta48ge-cleanall:
-	@$(MAKE) -f swdrvr-ta48ge.make cleanall
-	
-tg4g-cleanall:
-	@$(MAKE) -f swdrvr-tg4g.make cleanall
-
-tg16g-cleanall:
-	@$(MAKE) -f swdrvr-tg16g.make cleanall
-	
-tg16gf-cleanall:
-	@$(MAKE) -f swdrvr-tg16gf.make cleanall
-	
-tt04sxg-cleanall:
-	@$(MAKE) -f swdrvr-tt04sxg.make cleanall
-	
-olt1t0-cleanall:
-	@$(MAKE) -f swdrvr-olt1t0.make cleanall
-	
-olt1t0f-cleanall:
-	@$(MAKE) -f swdrvr-olt1t0f.make cleanall
-
-	
-cxo640g-install:
-	@sh cxo640g.install
-
-cxo160g-install:
-	@sh cxo160g.install
-
-ta48ge-install:
-	@sh ta48ge.install
-	
-tg4g-install:
-	@sh tg4g.install
-
-tg16g-install:
-	@sh tg16g.install
-	
-tg16gf-install:
-	@sh tg16gf.install
-	
-tt04sxg-install:
-	@sh tt04sxg.install
-	
-olt1t0-install:
-	@sh olt1t0.install
-	
-olt1t0f-install:
-	@sh olt1t0f.install
