Task OLTSWITCH-48 (merge from trunk-r3582,3583) Several bugs corrected at the building scripts.
svn path=/branches/3.6/; revision=3586

diff --git a/src/builds/buildFpAllInOne b/src/builds/buildFpAllInOne
--- a/src/builds/buildFpAllInOne
+++ b/src/builds/buildFpAllInOne
@@ -52,8 +52,8 @@ currentUser=$(whoami)
 ###############Validate Current User###################
 
 ############Paths Assignment & Validation#####################
-builderScriptPath=~/svnrepo/olt-switchsw/trunk/src/builds
-srcPath=~/svnrepo/olt-switchsw/trunk/src
+builderScriptPath=.
+srcPath=..
 buildPath=~/fastpath_builds
 mkBoardsPath=~/mkboards_$oltVersion
 
@@ -101,9 +101,11 @@ if  [ $updateSvn -eq 1 ]; then
 
 		exit $?
 	fi
-	svnRelease=$(svnversion $srcPath)
+	#svnRelease=$(svnversion $srcPath)
+	svnRelease=`svnversion ../fastpath -n | sed -e 's/.*://' -e 's/[A-Z]*$$//'`
 else	
-	svnRelease=$(svnversion $srcPath)
+	#svnRelease=$(svnversion $srcPath)
+	svnRelease=`svnversion ../fastpath -n | sed -e 's/.*://' -e 's/[A-Z]*$$//'`
 	echo "I'm not updating $srcPath: Using current svn release:$svnRelease...press Ctrl+C to abort"
 	sleep 1
 fi
@@ -130,9 +132,14 @@ cd $builderScriptPath
 if  [ $scriptDebugCommands -eq 1 ]; then
 	echo sh ./fastpath-olt.build $oltVersion.$patchVersion
 fi
-sh ./fastpath-olt.build $oltVersion.$patchVersion compile
+#sh ./fastpath-olt.build $oltVersion.$patchVersion compile
+#if [ $? -ne 0 ]; then
+#  echo "Error compiling boards!"
+#  exit -1;
+#fi
+sh ./fastpath-olt.build $oltVersion.$patchVersion install
 if [ $? -ne 0 ]; then
-  echo "Error compiling boards!"
+  echo "Error copying binaries!"
   exit -1;
 fi
 sh ./fastpath-olt.build $oltVersion.$patchVersion build
