Task OLTSWITCH-48 (merge from trunk-r3587) Corrected bug at the building scripts.
svn path=/branches/3.6/; revision=3588

diff --git a/src/builds/buildFpAllInOne b/src/builds/buildFpAllInOne
--- a/src/builds/buildFpAllInOne
+++ b/src/builds/buildFpAllInOne
@@ -132,11 +132,11 @@ cd $builderScriptPath
 if  [ $scriptDebugCommands -eq 1 ]; then
 	echo sh ./fastpath-olt.build $oltVersion.$patchVersion
 fi
-#sh ./fastpath-olt.build $oltVersion.$patchVersion compile
-#if [ $? -ne 0 ]; then
-#  echo "Error compiling boards!"
-#  exit -1;
-#fi
+sh ./fastpath-olt.build $oltVersion.$patchVersion compile
+if [ $? -ne 0 ]; then
+  echo "Error compiling boards!"
+  exit -1;
+fi
 sh ./fastpath-olt.build $oltVersion.$patchVersion install
 if [ $? -ne 0 ]; then
   echo "Error copying binaries!"
