Task OLTSWITCH-48 (merge from trunk-r3566,3567) buildFpAllInOne verifies errors during compilation or files copying. buildFpAllInOne has more input parameters to specify OLT version.
svn path=/branches/3.6/; revision=3577

diff --git a/src/builds/buildFpAllInOne b/src/builds/buildFpAllInOne
--- a/src/builds/buildFpAllInOne
+++ b/src/builds/buildFpAllInOne
@@ -5,38 +5,32 @@ scriptDebugCommands=0
 scriptVerbose=1
 ########End Debug Flags###########
 
-###############Input Arguments Validation#########################
-if [ $# -gt 1 ]; then
-   echo "Usage: sh ./builFpAllInOne [\$updateSvn]"   
-   exit -1
-fi
-
-if [ $# -eq 1 ]; then
-	updateSvn=$1
-	if  [ $updateSvn -ne 1 ]; then
-		if  [ $updateSvn -ne 0 ]; then
-			echo "Invalid Input Parameter: updateSvn=$updateSvn"
-			exit -1
-		fi
-	fi
-else
-	updateSvn=1
-fi
-
-if  [ $scriptDebugCommands -eq 1 ]; then
-	echo updateSvn=$updateSvn
-fi
-###############End Input Arguments Validation#########################
-
 ###########OLT Version and Patch Version##################
 oltVersion=3.6
 patchVersion=0
 
+###############Input Arguments Validation#########################
+echo "Usage: sh $0 [\$updateSvn] [version] [patch]"
+
+updateSvn=1
+if [ $# -ge 1 ]; then
+	updateSvn=$1
+	if  [ $updateSvn -ne 1 -a $updateSvn -ne 0 ]; then
+		echo "Invalid Input Parameter: updateSvn=$updateSvn"
+		exit -1
+	fi
+elif [ $# -ge 2 ]; then
+	oltVersion=$2
+elif [ $# -ge 3 ]; then
+	patchVersion=$3
+fi
+
 if  [ $scriptDebugCommands -eq 1 ]; then
+	echo updateSvn=$updateSvn
 	echo "oltVersion=$oltVersion"
 	echo "patchVersion=$patchVersion"
 fi
-############End OLT Version and Patch Version##################
+###############End Input Arguments Validation#########################
 
 ###############Save Current Path#########
 currentPath=$(pwd)
@@ -135,7 +129,15 @@ if  [ $scriptDebugCommands -eq 1 ]; then
 	echo sh ./fastpath-olt.build $oltVersion.$patchVersion
 fi
 sh ./fastpath-olt.build $oltVersion.$patchVersion compile
+if [ $? -ne 0 ]; then
+  echo "Error compiling boards!"
+  exit -1;
+fi
 sh ./fastpath-olt.build $oltVersion.$patchVersion build
+if [ $? -ne 0 ]; then
+  echo "Error transferring binaries!"
+  exit -1;
+fi
 
 if  [ $? -ne 0 ]; then
 	echo -e "
